name       : rtmpdump
version    : 2
release    : 1
source     :
    - http://rtmpdump.mplayerhq.hu/download/rtmpdump-2.3.tgz : ef38b7a99d82ce6912063d21063aeaf28185341b3df486e24bffce5354224b2c
license    : GPL-2.0
summary    : RTMP Dump
description: |
    RTMP Dump
build      : |
    %make
install    : |
    # Whiney package
    mkdir -p %installroot%/usr/local/lib/pkgconfig
    %make_install
    mv %installroot%/usr/local/bin %installroot%/usr/
    mv %installroot%/usr/local/include %installroot%/usr/
    mv %installroot%/usr/local/lib %installroot%/usr/
    mv %installroot%/usr/local/man %installroot%/usr/
    mv %installroot%/usr/local/sbin %installroot%/usr/
    rm -r %installroot%/usr/local
    rm %installroot%/usr/lib/librtmp.a
