name       : rtmpdump
version    : 2
release    : 2
source     :
    - http://rtmpdump.mplayerhq.hu/download/rtmpdump-2.3.tgz : ef38b7a99d82ce6912063d21063aeaf28185341b3df486e24bffce5354224b2c
license    : GPL-2.0
summary    : RTMP Dump
builddeps  :
    - pkgconfig32(zlib)
    - pkgconfig32(libssl)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    RTMP Dump
build      : |
    %make OPT="$CFLAGS" CC="$CC" XLDFLAGS="$LDFLAGS"
install    : |
    install -D -d -m 00755 $installdir
    install -D -d -m 00755 $installdir/%libdir%/pkgconfig
    %make_install prefix=/usr sbindir=/usr/bin mandir=/usr/share/man  libdir=%libdir%
    rm $installdir/%libdir%/*.a
